### PR TITLE
Fix compatibility with drjit 0.4.0

### PR DESCRIPTION
**Pull request by CorentinDumery**
Fixing a name conflict with newer versions of drjit, this should solve #1 . 

(Credits to Nicolas R)

### CODE REVIEW

**Comment by DoeringChristian** [comment]
There is also a bug which is somewhat related to this. Currently the prebuilt wheels do not work with the latest drjit version since some function names where changed. Therefore I get an undefined symbol error. The binaries would therefore have to be rebuilt for compatibility.

**Comment by InterstellarIntruder** [comment]
When do you expect this change will be made available? I am having an issue, and this fix would help me.

**Comment by dvicini** [comment]
Hi,

Sorry for this package getting a little stale! I was starting a new job and couldn't really keep up

@CorentinDumery Is this fix still something I should merge? Is this sufficient to update the package to the latest drjit?

Best
Delio

**Comment by dvicini** [comment]
I pushed a fix and will update the version of the build

**Pull request closed without merging**
